import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from 'next/link'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>

      <nav className="bg-blue-500 p-4">
        <div className="container mx-auto flex items-center justify-between">
          <a href="#" className="text-white text-lg font-semibold">Onboarding</a>
          <div className="flex space-x-2">
            <Link className='px-3 py-2 text-blue-100 no-underline bg-blue-500 rounded hover:bg-gray-600 hover:text-white-500' href="/document/list">Home</Link>
            <Link className='px-3 py-2 text-blue-100 no-underline bg-blue-500 rounded hover:bg-gray-600 hover:text-white-500' href="/document/create">Create New Document</Link>
          </div>
        </div>
      </nav>

      <div className="container mx-auto p-8">
        {children}
      </div>
      </body>
    </html>
  )
}
