import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from 'next/link'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>

      <nav className="bg-blue-500 p-4">
        <div className="container mx-auto flex items-center justify-between">
          <a href="#" className="text-white text-lg font-semibold">Your Logo</a>
          <div className="flex space-x-4">
            <Link href="/document/list">Home</Link>
            <Link href="/document/read">Profile</Link>
          </div>
        </div>
      </nav>

      <div className="container mx-auto p-8">
        <h1 className="text-4xl font-bold mb-8">Welcome to Your Website</h1>
        {children}
      </div>
      </body>
    </html>
  )
}
